# Generated by Django 4.0.2 on 2022-03-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('date_purchased', models.DateField()),
                ('nib_size', models.CharField(choices=[('B', 'Broad'), ('M', 'Medium'), ('F', 'Fine'), ('EF', 'Extra Fine')], max_length=2)),
            ],
        ),
    ]
