# Generated by Django 4.0.2 on 2022-03-09 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0002_ink'),
    ]

    operations = [
        migrations.AddField(
            model_name='pen',
            name='current_ink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pens.ink'),
        ),
    ]
